### ISSUE TITLE
Add ability to ignore some tests

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#113]
I can see a scenario where a user is well aware of something but would like to ignore a given test, for debugging purpose or whatever.

What about providing a way to disable some tests when using the Sass API? Would be fairly easy to implement I must say. I can think of something like this:

```scss
$disabled-tests: (
  "advices": ("target-blank")
);
```

**Comment by ffoodd** [comment]
Well, this is a good idea: I'm often embarrassed by some tests I can't fix myself and arealways showing up.

I do wonder: 
* How does this technically happen? I'm sure you're able to help on this :)
* Isn't this feature too much? I mean, I'm not sure that users (if there are) are all used to compile their own file. I still think this is a good idea, I'm just questionning its value for end users.

May another user give his opinion? @GaetanBt or @7studio for example?

**Comment by HugoGiraudel** [comment]
> How does this technically happen? I'm sure you're able to help on this :)

Current:

```scss
@mixin error($key, $self-closing: false) {
  @if is-level-enough("error") {
    @include item("error", $key, $self-closing);
  }
}
```

New: 

```scss
@mixin error($key, $self-closing: false) {
  $is-disabled: index(map-get($disabled-tests, 'error'), $key);

  @if is-level-enough("error") and not $is-disabled {
    @include item("error", $key, $self-closing);
  }
}
```
