### ISSUE TITLE
Better way to target void elements

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#115]
Some tests (such as with and height attributes) may target void elements and that's not taken in consideration yet. I'll need a way to easily duplicate large cases (empty class or id, for example) that could match a void tag, maybe a kind of list continaining every void elements?

See #84 for example.

**Comment by ffoodd** [comment]
We may use a simple list:
```
$tags: area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr, textarea, select, svg, audio, video, iframe;

@each $tag in $tags {
  #{$tag}[width] {
    @include level("message");
  }
}
```
which could basically work. We'll also need the ability to ignore some. Maybe a list for each case, but that sounds weird.
 
Didn't really think about it, but will do :D

**Comment by HugoGiraudel** [comment]
Don't loop.

```scss
$tags: area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr, textarea, select, svg, audio, video, iframe;

#{$tags} {
  &[width] {
    content: yo;
  }
}
```
