### ISSUE TITLE
Stocker le z-index maximum en variable

### ISSUE THREAD

**Issue by KittyGiraudel** [ffoodd/a11y.css#14]
`2147483647` est typiquement le genre de valeur que l'on ne veut pas répéter. ;)

Ca permettrait aussi de rendre le code plus élégant : 

``` scss
$max-z-index: 2147483647;

@if $level == "forestgreen" {
  z-index: $max-z-index - 3 !important;
} @else if $level == "gray" {
  z-index: $max-z-index - 2 !important;
} @else if $level == "gold" {
  z-index: $max-z-index - 1 !important;
} @else if $level == "crimson" {
  z-index: $max-z-index     !important;
}
```
