### ISSUE TITLE
Possibility to prefix with class names?

### ISSUE THREAD

**Issue by DiemenDesign** [ffoodd/a11y.css#280]
I'd like to be able to ally.css inside the Summernote Editor, but only show warnings inside the editor area, not the whole page the editor resides in like `.note-editing-area .a11y html{counter-reset:error warning obsolete advice}` (just for e.g.), I couldn't see where I can add this before building a11y.css.

The `.note-editing-area` is the class Sumernote uses for it's editing area (duh), and the `.a11y` class is the class I wish to toggle to programmatically add and remove the warning messages.

**Comment by ffoodd** [comment]
Very interesting question, thanks!

As a simple answer, you can do this by simply wrap imports in main files. Example in `a11y-fr_errors-only.scss`:

```scss
@charset 'UTF-8';

$messages: require('./locales/fr', $infer: false);

.summernote {
  @import 'utils/all';
  @include set-minimum-level('error');
  @import 'base/base';
  @import 'themes/error';
}
```

But it wouldn't work as expected.

First things first: 
* in fact, since Summernote isn't using an `<iframe>`, the `sass/base/_base.scss` file would be maladjusted since it's starting from `html` and `body` to show counters. Using it in Summernote will require to customize those two selectors (using `.note-editing-area ` instead of `html` and `.a11y` in lieu of `body`).
* by doing this, a few tests would become useless (like testing `<head>`'s children or `<html>` tag directly). You might want to disable those.

Setting main selectors as variable is possible, but I don't think I'll include it in a11y.css since (as I just said) it would prevent some major tests to work.

However, by forking the project and using your custom build, you'd be able to make those changes for your project's context. :)

Did I answer your question?
