### ISSUE TITLE
Proposition : Amélioration progressive

### ISSUE THREAD

**Issue by 7studio** [ffoodd/a11y.css#4]
La propriété CSS `outline` est judicieusement utilisée et justifiée dans ce projet :

> on utilise outline plutôt que border afin de ne pas modifier les dimensions des éléments.

Cela étant, l'avantage principal dont nous profitons en utilisant cette propriété CSS n'est pas sans limites.
Dans des cas particuliers :
- gestion des débordements sur le bloc contenant à l'aide de `overflow: hidden`
- positionnement de l'élément contre un bord de la fenêtre du navigateur ou une scrollbar

les contours dessinés au-dessus du contenu en débordant (si nécessaire) du bloc contenant ne seront pas visibles.

Difficile alors de profiter pleinement du projet.

Afin de s'acquitter autant que possible des dépendances au contenant, je propose de dessiner les contours à l'intérieur des éléments grâce à la propriété CSS [`outline-offset`](https://developer.mozilla.org/fr/docs/CSS/outline-offset) associée à une valeur négative.
Voici les différences visibles sur un exemple simple : http://jsfiddle.net/7studio/sRExL/

Internet Explorer n'offrant toujours pas de support à cette propriété (même dans sa version 11), cette proposition devra être considérée comme une amélioration progressive (« bonus » pour les utilisateurs disposant de navigateurs plus récents ou plus évolués) du projet.

Voici la modification qui serait nécessaire :

``` scss
// -- @subsection Mixins --------------------
@mixin outline( $level ) {
  outline: 4px solid transparentize( $level, .25 ) !important;
  outline-offset: -4px;

  ...

}
```

Qu'en pensez-vous ?

Ressources supplémentaires :
- http://caniuse.com/#feat=outline
- http://dev.w3.org/csswg/css-ui/#outline-offset
