### ISSUE TITLE
Show schema.org metadata

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#495]
For SEO folks, an [easy to use selector to highlight itemprops, by Terence Eden (on Mastodon)](https://mastodon.social/@Edent/113539855185175855).

Basically:

```css
[itemprop]::after {
    content: "itemprop" attr(itemtype);
}
```

Or something?
