### ISSUE TITLE
Proposition: Cas particuliers des balises auto-fermantes

### ISSUE THREAD

**Issue by 7studio** [ffoodd/a11y.css#6]
> Les balises «auto-fermantes» n’autorisent pas la génération de contenu. Ainsi les erreurs ou alertes seront marquées mais aucun message n’apparaitra au survol.

Même si les messages seront parfois consultables grâce aux inspecteurs de DOM (Chrome, IE11), il n'est pas envisageable que cela soit une solution acceptable pour un problème que je considère comme bloquant pour profiter pleinement de l'outil.
### Proposition

Utiliser le sélecteur combinateur [`~`](https://developer.mozilla.org/fr/docs/CSS/S%C3%A9lecteurs_de_voisins_g%C3%A9n%C3%A9raux) qui permet de cibler des éléments suivants du même niveau dans un élément parent commun.
Ce sélecteur va permettre aux éléments «auto-fermants» de demander aux suivants (à condition qu'ils existent et puissent) d'afficher les erreurs ou alertes pour eux.
Afin de ne pas perturber (avec une information qui n'est pas la leur) les éléments qui seraient eux-mêmes en erreur, en alerte, obsolètes ou pouvant être améliorés, la gestion des messages devra être traitée **uniquement** lorsque cela sera nécessaire (au survol de l'élément dans notre cas).

Voici à quoi cela ressemblerait théoriquement dans le cas de l'élément `<img />` :

``` css
img:not([alt]),
img[alt=""],
img[alt=" "] {
  outline: 4px solid rgba(220, 20, 60, .75) !important;
  outline-offset: -4px;
}
img:not([alt]):hover ~ *::after,
img[alt=""]:hover ~ *::after,
img[alt=" "]:hover ~ *::after {

  /* @extend %message; */

  z-index: 2147483647 !important;
}
img:not([alt]):hover ~ *::after { content: "\26D4\00A0 Attribut [alt] manquant. Quelle hérésie." !important; }
img[alt=""]:hover    ~ *::after { content: "\26A0\00A0 Attribut [alt] vide. C’est toléré pour les images de décoration uniquement. Est-ce le cas ?" !important; }
img[alt=" "]:hover   ~ *::after { content: "\26D4\00A0 Un attribut [alt] *presque* vide. C’est une blague, non ?" !important; }
```

J'ai également mis cet exemple en pratique dans un Fiddle : http://jsfiddle.net/7studio/X7y8e/.

Cette méthode n'est malheureusement pas parfaite et échouera (le message n'apparaîtra pas au survol) dans plusieurs cas **très** particuliers :
- L'élément est le seul enfant de son élément parent
- L'élément est suivi uniquement par des éléments eux-mêmes «auto-fermants»

Néanmoins cette proposition permettra de nous aider dans de nombreux cas.

Qu'en pensez-vous ?
